### ISSUE TITLE
Subsetting the woff2 version of Google Web Fonts fails

### ISSUE THREAD

**Issue by papandreou** [assetgraph/assetgraph#901]
```
$ bringhome webdevcph1.1prod.one -o webdevcph1 -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36' && subfont -i webdevcph1/index.html
[...]
Error: subsetFonts transform: Could not find a supported cmap table
    at new CmapProcessor (/home/andreas/work/assetgraph/node_modules/fontkit/index.js:3869:13)
    at WOFFFont.get (/home/andreas/work/assetgraph/node_modules/fontkit/index.js:14111:14)
    at WOFFFont.descriptor.get (/home/andreas/work/assetgraph/node_modules/fontkit/index.js:95:23)
    at WOFFFont.get (/home/andreas/work/assetgraph/node_modules/fontkit/index.js:14122:19)
    at WOFFFont.descriptor.get (/home/andreas/work/assetgraph/node_modules/fontkit/index.js:95:23)
    at subsetFonts (/home/andreas/work/assetgraph/lib/transforms/subsetFonts.js:658:13)
    at <anonymous>
```

It fails because fontkit's `characterSet` getter throws here: https://github.com/assetgraph/assetgraph/blob/2c9350ec602a9ece4a52547a845dcb4567c2d799/lib/transforms/subsetFonts.js#L612

Even though `fontkit.create(fontUsage.subsets.woff).directory.tables.cmap` is tthere:

```js
{ tag: 'cmap',
  offset: 508,
  compLength: 4,
  length: 4,
  origChecksum: 0 }
```

**Comment by papandreou** [comment]
Funny thing is that fontkit seems to read the character set of the original woff2 files from Google just fine:

```
$ curl -s0 -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36' http://fonts.googleapis.com/css?family=Roboto | grep -A10 -F 'latin */'
```

```css
/* latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(http://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

```
$ curl -s0 -O http://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
$ node -p "require('fontkit').openSync('KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2').characterSet"
[ 0,
  13,
  32,
  33,
  34,
  35,
  36,
...
```
